.gitignore, sqlflow/dbapi/__init__.py, sqlflow/dbapi/connection.py, sqlflow/dbapi/cursor.py
=> Add a DBAPI skeleton

.gitignore, Makefile, README.md, setup.py, sqlflow/__version__.py, sqlflow/dbapi/__init__.py
It only includes setup development environment and generate GRPC client code
=> add make file

setup.py, sqlflow/magic.py, tests/test_magic.py
Fix: https://github.com/ktong/pysqlflow/issues/15
@ktong Not sure how to test it... Should we mock the client to avoid a standalone go server?
=> [WIP] add magic and test framework

sqlflow/client.py, tests/test_client.py
=> Change client to adapt row based protobuf

.gitignore, .travis.yml, tests/mock_servicer.py, tests/test_client.py
=> Add mock server for grpc client_test

tests/mock_servicer.py, tests/test_client.py
Fix bug: #17 
Mock server should return a table response for request sql like `select * from glaxy;`
=> Fix grpc mock server bug

.travis.yml
=> [Release] update deploy user and passwd

.travis.yml
=>  enable deploy build on new tags

setup.py
=> [release] setup.py should include generated proto files

README.md
=> fix pypi project name

sqlflow/client.py
output of error:
```
line1: errorCode # we use errorCode to treat server error, network error as difference
line2: details
```
example:
```
In [2]: %%sqlflow select * from iris.iris limit 1; -- normal
...: 
...: 
Out[2]: 
+--------------+-------------+--------------+-------------+-------+
| sepal_length | sepal_width | petal_length | petal_width | class |
+--------------+-------------+--------------+-------------+-------+
|     6.4      |     2.8     |     5.6      |     2.2     |   2   |
+--------------+-------------+--------------+-------------+-------+
In [3]: %%sqlflow select * from iris.iris notlimit 1; -- bad sql
...: 
...: 
StatusCode.UNKNOWN
runQuery failed: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the …
```
=> Handling grpc exception

.travis.yml, README.md, doc/desigin/client_design_doc.md, setup.py
=> Rename wangkuiyi to sql-machine-learning

sqlflow/magic.py
=> Make magic command support SQL syntax

sqlflow/__main__.py, sqlflow/client.py, tests/mock_servicer.py, tests/test_client.py
=> SQLFlow gRPC client supports TSL/SSL 

sqlflow/client.py, sqlflow/magic.py
Fixed https://github.com/sql-machine-learning/sqlflow/issues/416
=> [bug fix]: print logs repeatedly

proto/sqlflow/proto/sqlflow.proto, sqlflow/client.py, tests/mock_servicer.py, tests/test_client.py
Related PR: https://github.com/sql-machine-learning/sqlflow/pull/594
=> suspport send exit_on_submit

proto/sqlflow/proto/sqlflow.proto, sqlflow/client.py, tests/mock_servicer.py, tests/test_client.py
Related PR: https://github.com/sql-machine-learning/sqlflow/pull/596
=> send user_id in session

sqlflow/__init__.py, sqlflow/client.py, sqlflow/env_expand.py, tests/test_client.py, tests/test_env_expand.py
=> [feature] env expander

sqlflow/env_expand.py, tests/test_env_expand.py
=> support arbitrary space

setup.py, sqlflow/rows.py
=> Add to_dataframe and better data presentation

sqlflow/__main__.py, sqlflow/client.py, tests/test_client.py
=> Add support for command line

sqlflow/__main__.py, sqlflow/client.py, sqlflow/compound_message.py, tests/test_client.py
Fix: https://github.com/sql-machine-learning/sqlflow/issues/1017
Display compound message like:
=> fix compound message display on notebook

proto/sqlflow/proto/sqlflow.proto, sqlflow/client.py, sqlflow/compound_message.py
Fix https://github.com/sql-machine-learning/sqlflow/issues/1007
=> pass hive location from client
